package version

import (
	"flag"
	"fmt"
	"os"
)

// generated by -ldflags "-X main.name=version". DO NOT EDIT.
var (
	Commit    = "unknown"
	BuildTime = "unknown"
	GoVersion = "unknown"
)

func init() {
	version := flag.Bool("v", false, "print version")
	flag.Parse()
	if *version {
		fmt.Printf("dstore manager\nCommit: %v\nBuildTime: %v\nGoVersion: %v\n", Commit, BuildTime, GoVersion)
		os.Exit(0)
	}
}
